apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./sredx-team-group.yaml
    - ./plateform-team-group.yaml
    - ./mfa-team-group.yaml
    - ./kyc-team-group.yaml
    - ./accelerate-team-group.yaml
    - ./users/faissal_elfid.yaml
    - ./users/mohamed_zerouali.yaml
    - ./cooptation-team-group.yaml
    - ./users/cooptation/abdelati-elouadi.yaml
    - ./users/cooptation/anas-idrissi.yaml
    - ./users/cooptation/yassine-naciri.yaml
